spring:
  application:
    name: ${APP_NAME:unnamed}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${URL:jdbc:mariadb://localhost/contact?useSSL=false&characterEncoding=utf8}
    username: ${USERNAME:user}
    password: ${PASSWORD:password}